package com.example.holymoly

import android.util.Log
import com.google.firebase.firestore.ktx.firestore
import com.google.firebase.ktx.Firebase
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.tasks.await
import kotlinx.coroutines.withContext

class FirestoreHelper {
    private val db = Firebase.firestore
    //firestore에서 이메일 가져오기
    val authHelper = AuthHelper()
    val userEmail = authHelper.getCurrentUserEmail()
    fun addUserToFirestore(email: String) {

        val data = hashMapOf("user_email" to email)

        db.collection("user").document(email)
            .set(data)
            .addOnSuccessListener { Log.d(TAG, "DocumentSnapshot successfully written!") }
            .addOnFailureListener { e -> Log.w(TAG, "Error writing document", e) }
    }


    fun addHolidayToFirestore(holiday_title:String, start_year: Int, start_month:Int, start_date:Int,
                              end_year:Int, end_month:Int, end_date:Int, category:Int) {
        val data = hashMapOf(
            "holiday_title" to holiday_title,
            "start_year" to start_year,
            "start_month" to start_month,
            "start_date" to start_date,
            "end_year" to end_year,
            "end_month" to end_month,
            "end_date" to end_date,
            "category" to category)

        db.collection("user").document(userEmail!!).
        collection("holiday").add(data)
            .addOnSuccessListener { documentReference ->
                // 성공적으로 데이터 추가됨
                Log.d(TAG, "Document successfully added with autogenerated ID: ${documentReference.id}")
            }
            .addOnFailureListener { e ->
                // 데이터 추가 실패
                Log.w(TAG, "Error adding document", e)
            }

    }

    suspend fun getMonthHolidaysFromFirestore(this_month:Int): List<Map<String, Any>> {
        return withContext(Dispatchers.IO) {
            try {
                val documents_start = db.collection("user")
                    .document(userEmail!!)
                    .collection("holiday")
                    .whereEqualTo("start_month", this_month)
                    .get()
                    .await()

                val documents_end = db.collection("user")
                    .document(userEmail!!)
                    .collection("holiday")
                    .whereEqualTo("end_month", this_month)
                    .get()
                    .await()

                Log.d("ny", "Number of documents: ${documents_start.size()}")
                Log.d("ny", "Number of documents: ${documents_end.size()}")

                val holidayList = mutableListOf<Map<String, Any>>()

                for (document in documents_start) {
                    // 각 문서에 대한 처리
                    val data = document.data
                    // data를 사용하여 필요한 작업 수행
                    holidayList.add(data)
                }

                for (document in documents_end) {
                    // 각 문서에 대한 처리
                    val data = document.data
                    // data를 사용하여 필요한 작업 수행
                    if (!holidayList.contains(data)) {
                        holidayList.add(data)
                    }
                }
                return@withContext holidayList
            } catch (exception: Exception) {
                // 쿼리 실패 시 처리
                Log.w(TAG, "Error getting documents: ", exception)
                return@withContext emptyList() // 실패할 경우 빈 리스트 반환 또는 예외처리 방식에 따라 변경
            }
        }
    }

    suspend fun getAllHolidaysFromFirestore(): List<Map<String, Any>> {
        return withContext(Dispatchers.IO) {
            try {
                val documents = db.collection("user")
                    .document(userEmail!!)
                    .collection("holiday")
                    .get()
                    .await()

                val holidayList = mutableListOf<Map<String, Any>>()

                for (document in documents) {
                    // 각 문서에 대한 처리
                    val data = document.data
                    // data를 사용하여 필요한 작업 수행
                    holidayList.add(data)
                }

                return@withContext holidayList
            } catch (exception: Exception) {
                // 쿼리 실패 시 처리
                Log.w(TAG, "Error getting documents: ", exception)
                return@withContext emptyList() // 실패할 경우 빈 리스트 반환 또는 예외처리 방식에 따라 변경
            }
        }
    }

    suspend fun deleteHolidaysFromFirestore(holiday_title: String): List<Map<String, Any>> {
        return withContext(Dispatchers.IO) {
            try {
                // 해당 holiday_title을 가진 문서를 찾기
                val querySnapshot = db.collection("user")
                    .document(userEmail!!)
                    .collection("holiday")
                    .whereEqualTo("holiday_title", holiday_title)
                    .get()
                    .await()

                // 찾은 문서를 모두 삭제
                for (document in querySnapshot.documents) {
                    document.reference.delete().await()
                }

                // 삭제된 결과를 반환 (예: 삭제된 문서의 정보)
                // 여기서는 빈 리스트를 반환하도록 하였습니다.
                return@withContext emptyList()
            } catch (exception: Exception) {
                // 쿼리 실패 시 처리
                Log.w(TAG, "Error getting documents: ", exception)
                return@withContext emptyList() // 실패할 경우 빈 리스트 반환 또는 예외처리 방식에 따라 변경
            }
        }
    }
    companion object {
        private const val TAG = "FirestoreHelper"
    }

}